import type { Metadata } from "next";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import "@ant-design/v5-patch-for-react-19";
import ConfigWrapper from "@/components/base/config";

export const metadata: Metadata = {
  title: "运营管理后台",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AntdRegistry>
          <ConfigWrapper>{children}</ConfigWrapper>
        </AntdRegistry>
      </body>
    </html>
  );
}
